name: ci

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Debug file structure
        run: ls -R

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and test
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          target: test
          load: true

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          platforms: linux/amd64,linux/arm64
          push: true
          target: final
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/restcountries:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      - name: Set up Docker context
        run: docker context use default

      - name: Pull latest image
        run: docker-compose pull

      - name: Deploy with Docker Compose
        run: docker-compose up -d --build

      - name: Verify services
        run: docker-compose ps
